// Shapes the extension consumes from services/audiusApi.js (post-unwrap).
// Authoritative spec: https://api.audius.co/v1/swagger.yaml

export interface ImageObject {
    '150x150'?: string;
    '480x480'?: string;
    '1000x1000'?: string;
    '640x'?: string;
    '2000x'?: string;
    mirrors?: string[];
}

export interface User {
    id: string;
    user_id: number;
    handle: string;
    handle_lc: string;
    name: string;
    bio: string | null;
    location: string | null;
    is_verified: boolean;
    verified_with_twitter: boolean;
    verified_with_instagram: boolean;
    verified_with_tiktok: boolean;
    twitter_handle: string | null;
    instagram_handle: string | null;
    tiktok_handle: string | null;
    website: string | null;
    donation: string | null;
    profile_picture: ImageObject;
    cover_photo: ImageObject;
    profile_picture_sizes: string | null;
    cover_photo_sizes: string | null;
    follower_count: number;
    followee_count: number;
    track_count: number;
    playlist_count: number;
    album_count: number;
    repost_count: number;
    supporter_count: number;
    supporting_count: number;
    is_available: boolean;
    is_deactivated: boolean;
    erc_wallet: string;
    spl_wallet: string;
    spl_usdc_payout_wallet: string | null;
    wallet: string;
    payout_wallet: string;
    artist_pick_track_id: string | null;
    artist_coin_badge: unknown | null;
    coin_flair_mint: string | null;
    allow_ai_attribution: boolean;
    created_at: string;
    updated_at: string;
}

export interface Track {
    id: string;
    track_id: number;
    title: string;
    slug: string;
    permalink: string;
    description: string | null;
    genre: string;
    mood: string | null;
    tags: string | null;
    duration: number;
    release_date: string;
    artwork: ImageObject;
    user: User;
    play_count: number;
    repost_count: number;
    favorite_count: number;
    comment_count: number;
    is_streamable: boolean;
    is_downloadable: boolean;
    is_original_available: boolean;
    track_cid: string;
    preview_cid: string | null;
    orig_file_cid: string;
    orig_filename: string;
    ddex_app: string | null;
    playlists_containing_track: number[];
    pinned_comment_id: string | null;
    album_backlink: string | null;
    remix_of: { tracks: null | unknown[] };
}

export interface Playlist {
    id: string;
    permalink: string;
    playlist_name: string;
    description: string;
    is_album: boolean;
    is_image_autogenerated: boolean;
    artwork: ImageObject;
    track_count: number;
    repost_count: number;
    favorite_count: number;
    total_play_count: number;
    user: User;
    playlist_contents: Array<{ metadata_timestamp: number; timestamp: number; track_id: string }>;
    access: { stream: boolean; download: boolean };
    upc: string | null;
    ddex_app: string | null;
}

export interface UrlInfo {
    isArtistPage: boolean;
    isContentPage: boolean;
    artistHandle: string | null;
    contentId: string | null;
    contentType: 'artist' | 'track' | 'album' | 'playlist' | null;
}
