export interface ImageSizes {
    '150x150'?: string;
    '480x480'?: string;
    '1000x1000'?: string;
    '640x'?: string;
    '2000x'?: string;
    [key: string]: string | undefined;
}

export interface ArtistProfile {
    name: string;
    handle: string;
    bio: string;
    location: string;
    profilePicture: ImageSizes;
    coverPhoto: ImageSizes;
    followers: number;
    following: number;
}

export interface ArtistData {
    [handle: string]: {
        profile: ArtistProfile;
        tracks: Track[];
        playlists: Playlist[];
    };
}

export interface Track {
    id: string;
    title: string;
    description: string;
    artwork: ImageSizes;
    duration: number;
    genre: string;
    mood: string;
    tags: string[];
    releaseDate: string;
}

export interface Playlist {
    id: string;
    title: string;
    description: string;
    artwork: ImageSizes;
    trackCount: number;
    tracks: Track[];
}

export interface TabInfo {
    tabId: number;
    url: string;
    artistId?: string;
    status: 'loading' | 'ready' | 'error';
}

export interface ExtensionState {
    activeTabs: TabInfo[];
    selectedArtists: string[];
    downloadStatus: {
        [artistId: string]: 'pending' | 'downloading' | 'completed' | 'error';
    };
}

export interface TrackResponse {
    data: {
        artwork: {
            "150x150": string;
            "480x480": string;
            "1000x1000": string;
        };
        description: string | null;
        genre: string;
        id: string;
        track_cid: string;
        preview_cid: string | null;
        orig_file_cid: string;
        orig_filename: string;
        is_original_available: boolean;
        mood: string | null;
        release_date: string;
        remix_of: {
            tracks: null | Array<any>;
        };
        repost_count: number;
        favorite_count: number;
        comment_count: number;
        tags: string;
        title: string;
        user: UserData;
        duration: number;
        is_downloadable: boolean;
        play_count: number;
        permalink: string;
        is_streamable: boolean;
        ddex_app: string | null;
        playlists_containing_track: number[];
        pinned_comment_id: string | null;
        album_backlink: string | null;
    }
}

export interface PlaylistResponse {
    data: Array<{
        artwork: {
            "150x150": string;
            "480x480": string;
            "1000x1000": string;
        };
        description: string;
        permalink: string;
        id: string;
        is_album: boolean;
        is_image_autogenerated: boolean;
        playlist_name: string;
        playlist_contents: Array<{
            metadata_timestamp: number;
            timestamp: number;
            track_id: string;
        }>;
        repost_count: number;
        favorite_count: number;
        total_play_count: number;
        user: UserData;
        ddex_app: string | null;
        access: {
            stream: boolean;
            download: boolean;
        };
        upc: string | null;
        track_count: number;
    }>;
}

export interface UserData {
    album_count: number;
    artist_pick_track_id: string | null;
    bio: string;
    cover_photo: {
        "640x": string;
        "2000x": string;
    };
    followee_count: number;
    follower_count: number;
    handle: string;
    id: string;
    is_verified: boolean;
    twitter_handle: string | null;
    instagram_handle: string | null;
    tiktok_handle: string | null;
    verified_with_twitter: boolean;
    verified_with_instagram: boolean;
    verified_with_tiktok: boolean;
    website: string | null;
    donation: string | null;
    location: string;
    name: string;
    playlist_count: number;
    profile_picture: {
        "150x150": string;
        "480x480": string;
        "1000x1000": string;
    };
    repost_count: number;
    track_count: number;
    is_deactivated: boolean;
    is_available: boolean;
    erc_wallet: string;
    spl_wallet: string;
    spl_usdc_payout_wallet: string | null;
    supporter_count: number;
    supporting_count: number;
    total_audio_balance: number | null;
    wallet: string;
} 